import classfile

spk_inventory = classfile.Inventory('Spokane_inventory.csv')
md_inventory = classfile.Inventory('Mead_inventory.csv')

print(spk_inventory.search(year='2004', make='subaru', model='legacy', displacement=3.0))
print(spk_inventory.search(year='1995', make='subaru', model='impreza'))
print(spk_inventory.search(year='2000', make='toyota'))
print(spk_inventory.search(year=1999))
print(spk_inventory.search(make='chevy'))
print(spk_inventory.search(make='nissan'))
print(spk_inventory.search(make='datsun'))
print(spk_inventory.search(model='f150'))
print(spk_inventory.search(model='golf'))
print(spk_inventory.search(displacement=2.5))
print(spk_inventory.search(cylinders=6))
print(spk_inventory.search(model='impreza', displacement=2.2))
print(spk_inventory.search(model='Legacy', cylinders=4))
print(spk_inventory.search(year=1995, displacement=4.4))
print(spk_inventory.search(make='mercedes', cylinders=6))
print(spk_inventory.search(make='volkswagen', displacement=3.2))
print(spk_inventory.search(make='bmw', displacement=2.5))
print(spk_inventory.search())
